// src/components/Widgets/widgetRegistry.js - ADMIN PANEL DESIGN: Professional widget definitions
import { 
  TrendingUp,
  BarChart3,
  PieChart,
  Table2,
  Type,
  AlertCircle,
  Activity,
  List,
  Layers,
  Users,
  DollarSign,
  ShoppingCart,
  CheckSquare
} from 'lucide-react';

export const WIDGET_TYPES = {
  // ==================== METRICS (Admin Info Boxes) ====================
  metric: {
    id: 'metric',
    name: 'Info Box',
    category: 'metrics',
    description: 'Admin-style metric card with icon and trend',
    icon: TrendingUp,
    minW: 4,
    minH: 2,
    defaultWidth: 6,
    defaultHeight: 2,
    defaultProps: {
      label: 'Total Revenue',
      value: '€45,231',
      trend: '+12.5%',
      trendDirection: 'up',
      comparison: 'from last month',
      iconType: 'revenue',
      color: 'blue', // blue, green, purple, orange, red, cyan
      showProgress: false,
      progress: 75,
      backgroundColor: '#ffffff',
    },
  },

  statGrid: {
    id: 'statGrid',
    name: 'Stat Cards',
    category: 'metrics',
    description: 'Grid of metric cards for dashboards',
    icon: Layers,
    minW: 8,
    minH: 4,
    defaultWidth: 24,
    defaultHeight: 4,
    defaultProps: {
      title: 'Overview',
      stats: [
        { label: 'Total Users', value: '8,420', change: '+12%', status: 'positive', description: 'New users this week' },
        { label: 'Revenue', value: '€65.2K', change: '+8%', status: 'positive', description: 'Sales revenue' },
        { label: 'Orders', value: '1,843', change: '-3%', status: 'negative', description: 'Pending orders' },
        { label: 'Bounce Rate', value: '42.3%', change: '-2.5%', status: 'positive', description: 'User engagement' },
      ],
      columns: 4,
      backgroundColor: '#f8f9fa',
    },
  },

  // ==================== CHARTS ====================
  lineChart: {
    id: 'lineChart',
    name: 'Line Chart',
    category: 'charts',
    description: 'Line chart for trends over time',
    icon: Activity,
    minW: 8,
    minH: 5,
    defaultWidth: 12,
    defaultHeight: 6,
    defaultProps: {
      title: 'Sales Overview',
      subtitle: 'Monthly performance',
      data: [
        { month: 'Jan', value: 4200 },
        { month: 'Feb', value: 3800 },
        { month: 'Mar', value: 5100 },
        { month: 'Apr', value: 4600 },
        { month: 'May', value: 6200 },
        { month: 'Jun', value: 5800 },
      ],
      xAxisKey: 'month',
      yAxisKey: 'value',
      lineColor: '#3b82f6',
      showGrid: true,
      showDots: true,
      smooth: true,
      showLegend: false,
      backgroundColor: '#ffffff',
    },
  },

  barChart: {
    id: 'barChart',
    name: 'Bar Chart',
    category: 'charts',
    description: 'Bar chart for comparing values',
    icon: BarChart3,
    minW: 8,
    minH: 5,
    defaultWidth: 12,
    defaultHeight: 6,
    defaultProps: {
      title: 'Sales by Category',
      subtitle: 'Top performing categories',
      data: [
        { category: 'Electronics', value: 8500 },
        { category: 'Clothing', value: 6200 },
        { category: 'Home & Garden', value: 4800 },
        { category: 'Sports', value: 3900 },
        { category: 'Books', value: 2100 },
      ],
      xAxisKey: 'category',
      yAxisKey: 'value',
      barColor: '#3b82f6',
      showGrid: true,
      horizontal: false,
      showLegend: false,
      backgroundColor: '#ffffff',
    },
  },

  pieChart: {
    id: 'pieChart',
    name: 'Pie Chart',
    category: 'charts',
    description: 'Pie/Donut chart for proportions',
    icon: PieChart,
    minW: 6,
    minH: 5,
    defaultWidth: 8,
    defaultHeight: 6,
    defaultProps: {
      title: 'Traffic Sources',
      subtitle: 'Visitor distribution',
      data: [
        { name: 'Direct', value: 4500, color: '#3b82f6' },
        { name: 'Organic Search', value: 3200, color: '#10b981' },
        { name: 'Social Media', value: 2100, color: '#8b5cf6' },
        { name: 'Referral', value: 1200, color: '#f59e0b' },
        { name: 'Email', value: 800, color: '#ec4899' },
      ],
      showLegend: true,
      showLabels: true,
      donut: true,
      backgroundColor: '#ffffff',
    },
  },

  // ==================== DATA DISPLAY ====================
  table: {
    id: 'table',
    name: 'Data Table',
    category: 'data',
    description: 'Professional data table with status badges',
    icon: Table2,
    minW: 10,
    minH: 5,
    defaultWidth: 24,
    defaultHeight: 6,
    defaultProps: {
      title: 'Recent Orders',
      subtitle: 'Latest transactions',
      columns: [
        { key: 'id', label: 'Order ID', width: '15%' },
        { key: 'customer', label: 'Customer', width: '25%' },
        { key: 'product', label: 'Product', width: '25%' },
        { key: 'amount', label: 'Amount', width: '15%', type: 'number' },
        { key: 'status', label: 'Status', width: '20%', type: 'status' },
      ],
      data: [
        { id: '#10234', customer: 'John Doe', product: 'MacBook Pro', amount: '€2,499', status: 'Completed' },
        { id: '#10235', customer: 'Jane Smith', product: 'iPhone 15', amount: '€1,199', status: 'Processing' },
        { id: '#10236', customer: 'Bob Johnson', product: 'iPad Air', amount: '€649', status: 'Shipped' },
        { id: '#10237', customer: 'Alice Brown', product: 'AirPods Pro', amount: '€279', status: 'Pending' },
        { id: '#10238', customer: 'Charlie Wilson', product: 'Apple Watch', amount: '€449', status: 'Completed' },
      ],
      striped: true,
      showHeader: true,
      showFooter: true,
      footerText: 'orders',
      totalCount: 156,
      backgroundColor: '#ffffff',
    },
  },

  list: {
    id: 'list',
    name: 'Activity List',
    category: 'data',
    description: 'List of recent activities or events',
    icon: List,
    minW: 5,
    minH: 4,
    defaultWidth: 8,
    defaultHeight: 5,
    defaultProps: {
      title: 'Recent Activity',
      items: [
        { label: 'New order #10234', description: '2 minutes ago', icon: 'check', iconColor: '#10b981' },
        { label: 'Payment received', description: '15 minutes ago', icon: 'check', iconColor: '#10b981' },
        { label: 'User registration', description: '1 hour ago', icon: 'info', iconColor: '#3b82f6' },
        { label: 'Support ticket opened', description: '2 hours ago', icon: 'alert', iconColor: '#f59e0b' },
      ],
      showIcons: true,
      showDividers: true,
      backgroundColor: '#ffffff',
    },
  },

  statusBoard: {
    id: 'statusBoard',
    name: 'Status Board',
    category: 'data',
    description: 'Track project or task status',
    icon: CheckSquare,
    minW: 6,
    minH: 5,
    defaultWidth: 12,
    defaultHeight: 6,
    defaultProps: {
      title: 'Active Projects',
      items: [
        { name: 'Website Redesign', status: 'in-progress', progress: 75, dueDate: 'Mar 15, 2026' },
        { name: 'Mobile App Development', status: 'in-progress', progress: 45, dueDate: 'Apr 20, 2026' },
        { name: 'API Integration', status: 'completed', progress: 100, dueDate: 'Feb 28, 2026' },
        { name: 'User Testing', status: 'pending', progress: 0, dueDate: 'May 5, 2026' },
      ],
      showProgress: true,
      statusColors: {
        completed: '#10b981',
        'in-progress': '#3b82f6',
        pending: '#6b7280',
        blocked: '#ef4444',
      },
      backgroundColor: '#ffffff',
    },
  },

  // ==================== CONTENT ====================
  heading: {
    id: 'heading',
    name: 'Section Heading',
    category: 'content',
    description: 'Section title text',
    icon: Type,
    minW: 4,
    minH: 1,
    defaultWidth: 24,
    defaultHeight: 1,
    defaultProps: {
      text: 'Dashboard Overview',
      level: 'h2',
      align: 'left',
      color: '#1e293b',
      backgroundColor: 'transparent',
    },
  },

  alert: {
    id: 'alert',
    name: 'Alert/Notice',
    category: 'content',
    description: 'Important notifications',
    icon: AlertCircle,
    minW: 6,
    minH: 2,
    defaultWidth: 12,
    defaultHeight: 2,
    defaultProps: {
      title: 'System Update',
      message: 'Scheduled maintenance on March 15, 2026 from 2:00 AM to 4:00 AM EST.',
      variant: 'info',
      dismissible: true,
      icon: true,
    },
  },
};

// Category metadata
export const WIDGET_CATEGORIES = {
  metrics: { label: 'Metrics & KPIs', icon: TrendingUp, order: 1 },
  charts: { label: 'Charts', icon: BarChart3, order: 2 },
  data: { label: 'Data & Lists', icon: Table2, order: 3 },
  content: { label: 'Content', icon: Type, order: 4 },
};