import { 
  Box, 
  FileText, 
  BarChart3, 
  Image as ImageIcon, 
  Calendar, 
  Map,
  TrendingUp 
} from 'lucide-react';

export const WIDGET_TYPES = {
  container: {
    id: 'container',
    name: 'Container',
    category: 'layout',
    description: 'A flexible container to organize other content',
    icon: Box,
    minW: 2,
    minH: 2,
    defaultWidth: 400,
    defaultHeight: 300,
    defaultProps: {
      title: 'Container',
      bgColor: '#ffffff',
      borderColor: '#e2e8f0',
      borderWidth: 1,
      borderRadius: 8,
      shadow: 'md',
      paddingTop: 16,
      paddingRight: 16,
      paddingBottom: 16,
      paddingLeft: 16,
    },
  },
  card: {
    id: 'card',
    name: 'Card',
    category: 'content',
    description: 'Display text content in a styled card',
    icon: FileText,
    minW: 2,
    minH: 2,
    defaultWidth: 400,
    defaultHeight: 250,
    defaultProps: {
      title: 'Card Title',
      content: 'Your content goes here. Edit this text in the properties panel.',
      bgColor: '#ffffff',
      titleSize: 'lg',
      titleColor: '#1e293b',
      textColor: '#64748b',
    },
  },
  stats: {
    id: 'stats',
    name: 'Statistics',
    category: 'data',
    description: 'Show key metrics and statistics',
    icon: TrendingUp,
    minW: 2,
    minH: 1,
    defaultWidth: 300,
    defaultHeight: 180,
    defaultProps: {
      title: 'Total Revenue',
      value: '$45,231',
      change: '+20.1%',
      description: 'From last month',
      bgColor: '#ffffff',
      valueColor: '#1e293b',
      accentColor: '#3b82f6',
      icon: 'trending-up',
    },
  },
  chart: {
    id: 'chart',
    name: 'Chart',
    category: 'data',
    description: 'Visualize data with various chart types',
    icon: BarChart3,
    minW: 3,
    minH: 3,
    defaultWidth: 500,
    defaultHeight: 350,
    defaultProps: {
      title: 'Analytics',
      bgColor: '#ffffff',
      chartType: 'line',
      primaryColor: '#3b82f6',
      secondaryColor: '#8b5cf6',
      showGrid: true,
      showLegend: true,
    },
  },
  image: {
    id: 'image',
    name: 'Image',
    category: 'media',
    description: 'Display images with various options',
    icon: ImageIcon,
    minW: 2,
    minH: 2,
    defaultWidth: 400,
    defaultHeight: 300,
    defaultProps: {
      url: 'https://images.unsplash.com/photo-1618005198919-d3d4b5a92ead?w=800',
      alt: 'Placeholder image',
      objectFit: 'cover',
      borderRadius: 8,
      showCaption: false,
      caption: '',
    },
  },
  calendar: {
    id: 'calendar',
    name: 'Calendar',
    category: 'productivity',
    description: 'Display a calendar view',
    icon: Calendar,
    minW: 3,
    minH: 3,
    defaultWidth: 450,
    defaultHeight: 400,
    defaultProps: {
      title: 'Calendar',
      bgColor: '#ffffff',
      primaryColor: '#3b82f6',
    },
  },
  map: {
    id: 'map',
    name: 'Map',
    category: 'location',
    description: 'Display an interactive map',
    icon: Map,
    minW: 3,
    minH: 3,
    defaultWidth: 500,
    defaultHeight: 400,
    defaultProps: {
      title: 'Map',
      bgColor: '#ffffff',
      primaryColor: '#3b82f6',
    },
  },
};